# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. 
on: #[push pull_request]
  # Triggers the workflow on push or pull request events but only for the master branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      #- name: Set up Rye
        #run: curl -sSf https://rye-up.com/get | RYE_INSTALL_OPTION="--yes" bash && source "$HOME/.rye/env"
      - name: Install just from crates.io
        uses: baptiste0928/cargo-install@v2
        with:
          crate: just


      - uses: extractions/setup-just@v1

      - name: install prerequisites
        run: rye sync

      - name: format check
        run: just check
      
      - name: codecov
        run: just cov
      
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true